# Production Environment — am-notification
environment: prod
replicaCount: 2

resources:
  limits:
    cpu: 1000m
    memory: 768Mi
  requests:
    cpu: 500m
    memory: 512Mi

vault:
  enabled: true
  secretPaths:
    mongodb:
      path: "secret/data/prod/infra/mongodb"
    kafka:
      path: "secret/data/prod/infra/kafka"
    notification:
      path: "secret/data/prod/services/am-notification"
    novu:
      path: "secret/data/prod/services/am-novu"
    identity-oidc:
      path: "secret/data/prod/services/am-identity"
    service-oauth:
      path: "secret/data/prod/services/am-notification"


env:
  APP_ENV: production
  LOG_LEVEL: INFO
