apiVersion: am.argocd/v1
kind: ServiceDeploy
service: am-subscription
enabled: true
owners: platform
source:
  repo: am-platform
  path: am-subscription/argocd.yaml
chart:
  repoURL: https://github.com/AM-Portfolio/am-pipelines.git
  path: helm/universal-chart
  targetRevision: main
helm:
  releaseName: am-subscription
  valuesPath: am-subscription/helm
valuesRepoURL: https://github.com/AM-Portfolio/am-platform.git
valuesTargetRevision: main
envs:
  prod:
    enabled: true
    namespace: am-apps-prod
