# Dev Environment — am-identity
environment: dev
replicaCount: 1

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi


vault:
  enabled: true
  secretPaths:
    otel:
      path: "apps/data/dev/infra/observability"
    identity:
      path: "apps/data/dev/services/am-identity"

ingress:
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: >-
      am-apps-dev-dev-global-cors@kubernetescrd,
      am-apps-dev-dev-strip-prefix@kubernetescrd
  hosts:
    - host: am-dev.asrax.in
      paths:
        - path: /identity
          pathType: Prefix

env:
  APP_ENV: dev
  LOG_LEVEL: DEBUG
