vault:
  secretPaths:
    keycloak:
      mappings:
        KEYCLOAK_URL: "KEYCLOAK_URL"
        KEYCLOAK_ADMIN_USER: "KEYCLOAK_ADMIN_USER"
        KEYCLOAK_ADMIN_PASSWORD: "KEYCLOAK_ADMIN_PASSWORD"
        KEYCLOAK_REALM: "KEYCLOAK_REALM"
        OIDC_DISCOVERY_URL: "OIDC_DISCOVERY_URL"
        OIDC_ISSUER: "OIDC_ISSUER"
        OIDC_JWKS_URL: "OIDC_JWKS_URL"
        OIDC_TOKEN_URL: "OIDC_TOKEN_URL"
        GOOGLE_CLIENT_ID: "GOOGLE_CLIENT_ID"
        GOOGLE_CLIENT_SECRET: "GOOGLE_CLIENT_SECRET"
        AM_IDENTITY_CLIENT_ID: "AM_IDENTITY_CLIENT_ID"
        AM_IDENTITY_CLIENT_SECRET: "AM_IDENTITY_CLIENT_SECRET"
        ALLOWED_GOOGLE_REDIRECT_URIS: "ALLOWED_GOOGLE_REDIRECT_URIS"
    auth:
      mappings:
        JWT_SECRET: "JWT_SECRET"
