apiVersion: am.argocd/v1
kind: ServiceDeploy
service: am-identity
enabled: true
owners: platform
source:
  repo: am-platform
  path: am-identity/argocd.yaml
chart:
  repoURL: https://github.com/AM-Portfolio/am-pipelines.git
  path: am-identity/argocd.yaml
  targetRevision: main
helm:
  releaseName: am-identity
  valuesPath: am-identity/helm
valuesRepoURL: https://github.com/AM-Portfolio/am-platform.git
valuesTargetRevision: main
envs:
  prod:
    enabled: true
    namespace: am-apps-prod
