vault:
  secretPaths:
    postgres:
      mappings:
        POSTGRES_HOST: "host"
        POSTGRES_USER: "username"
        POSTGRES_PASSWORD: "password"
        AM_SUBSCRIPTION_POSTGRES_HOST: "host"
        AM_SUBSCRIPTION_POSTGRES_PORT: "port"
        AM_SUBSCRIPTION_DB_NAME: "AM_SUBSCRIPTION_DB_NAME"
        AM_SUBSCRIPTION_DB_USER: "AM_SUBSCRIPTION_DB_USER"
        AM_SUBSCRIPTION_DB_PASSWORD: "AM_SUBSCRIPTION_DB_PASSWORD"
    subscription:
      mappings:
        AM_SUBSCRIPTION_CLIENT_ID: "AM_SUBSCRIPTION_CLIENT_ID"
        AM_SUBSCRIPTION_CLIENT_SECRET: "AM_SUBSCRIPTION_CLIENT_SECRET"
        LAGO_API_URL: "LAGO_API_URL"
        LAGO_ORG_API_KEY: "LAGO_ORG_API_KEY"
        LAGO_WEBHOOK_SECRET: "LAGO_WEBHOOK_SECRET"
        AM_LAGO_CLIENT_ID: "AM_LAGO_CLIENT_ID"
        AM_LAGO_CLIENT_SECRET: "AM_LAGO_CLIENT_SECRET"
        DEFAULT_PLAN_CODE: "DEFAULT_PLAN_CODE"
    lago:
      mappings:
        LAGO_API_URL: "LAGO_API_URL"
        LAGO_ORG_API_KEY: "LAGO_ORG_API_KEY"
    identity-oidc:
      mappings:
        OIDC_JWKS_URL: "OIDC_JWKS_URL"
        OIDC_ISSUER: "OIDC_ISSUER"
