name: Debug Python locally

on:
  push:
    branches:
      - feature/account-deletion

jobs:
  run-python:
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install and Run
        run: |
          pip install -r requirements.txt
          pip install ./libraries/am-platform-common ./libraries/am-platform-security
          export PYTHONPATH=$PWD/libraries/am-platform-common:$PWD/libraries/am-platform-security:$PWD/am-identity
          python am-identity/am_identity/main.py || echo "PYTHON CRASHED"
